server:
  port: 8097
security:
  ignored: /**

spring:
  datasource:
    url: jdbc:h2:file:D:\WorkSpace\Intellij\opal\testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  ## http://localhost:8097/h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect